PT-12013: Extend Refund API with Transaction Correlation Id
VirtoCommerce/vc-module-order pull request #343
Opened 2023-05-04 19:54 UTC by EugeneOkhriemnko

## Description

## References
### QA-test:
### Jira-link:

https://virtocommerce.atlassian.net/browse/PT-12013

### Artifact URL:

2023-05-05 09:25 UTC, ksavosteev approved these changes

2023-05-05 14:49 UTC, artem-dudarev requested changes

2023-05-05 14:49 UTC, artem-dudarev commented on src/VirtoCommerce.OrdersModule.Data.MySql/Migrations/20230504164555_AddTransactionId.cs
> +            migrationBuilder.Sql("update orderrefund set TransactionId = Id;");
```suggestion
            migrationBuilder.Sql("UPDATE OrderRefund SET TransactionId = Id;");
```

2023-05-11 07:58 UTC, artem-dudarev approved these changes

2023-05-11 11:37 UTC, merged