Pt 12357
VirtoCommerce/vc-module-order pull request #355
Opened 2023-06-05 08:35 UTC by basilkot

## Description

## References
### QA-test:
### Jira-link:
### Artifact URL:

2023-06-05 08:55 UTC, ksavosteev requested changes

2023-06-05 08:55 UTC, ksavosteev commented on src/VirtoCommerce.OrdersModule.Web/package.json
> +    "glob": "^10.2.6"
Undo

2023-06-05 08:55 UTC, ksavosteev commented on src/VirtoCommerce.OrdersModule.Web/webpack.config.js
> +        ...glob.sync("./Content/**/*.css", options)
Undo

2023-06-14 10:25 UTC, basilkot commented on src/VirtoCommerce.OrdersModule.Web/package.json
> +    "glob": "^10.2.6"
done

2023-06-14 10:25 UTC, basilkot commented on src/VirtoCommerce.OrdersModule.Web/webpack.config.js
> +        ...glob.sync("./Content/**/*.css", options)
done

2023-06-15 08:41 UTC, ksavosteev approved these changes

2023-06-21 07:31 UTC, ksavosteev approved these changes

2023-06-21 08:04 UTC, merged